// Minimal Arduino core shim so the UNMODIFIED .ino sketch source compiles and
// runs on a Linux host, with `Serial` bound to a (virtual) tty instead of UART0.
// Only what the sketches use is implemented: Serial.begin/write/print/read/available, delay().
#pragma once
#include <stdint.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <unistd.h>
#include <fcntl.h>
#include <termios.h>
#include <time.h>
#include <errno.h>

static void delay(unsigned long ms) {
  struct timespec ts = { (time_t)(ms / 1000), (long)(ms % 1000) * 1000000L };
  nanosleep(&ts, NULL);
}

class HardwareSerial {
 public:
  int fd = -1;
  uint8_t rx[4096];
  size_t rx_len = 0;

  void begin(unsigned long baud) {
    const char *path = getenv("MCU_TTY");
    if (!path) { fprintf(stderr, "MCU_TTY not set\n"); exit(2); }
    fd = open(path, O_RDWR | O_NOCTTY | O_NONBLOCK);
    if (fd < 0) { perror(path); exit(2); }
    struct termios t;
    if (tcgetattr(fd, &t) == 0) {
      cfmakeraw(&t);
      cfsetspeed(&t, baud == 115200 ? B115200 : B9600);
      tcsetattr(fd, TCSANOW, &t);
    }
    fprintf(stderr, "[mcu-sim] Serial.begin(%lu) on %s\n", baud, path);
  }
  void pump() {
    for (;;) {
      if (rx_len >= sizeof(rx)) return;
      ssize_t n = ::read(fd, rx + rx_len, sizeof(rx) - rx_len);
      if (n <= 0) return;
      rx_len += (size_t)n;
    }
  }
  int available() { pump(); return (int)rx_len; }
  int read() {
    pump();
    if (rx_len == 0) return -1;
    int b = rx[0];
    memmove(rx, rx + 1, --rx_len);
    return b;
  }
  size_t write(uint8_t b) {
    while (::write(fd, &b, 1) != 1) { if (errno != EAGAIN) return 0; }
    return 1;
  }
  size_t print(char c) { return write((uint8_t)c); }
};
static HardwareSerial Serial;

void setup();
void loop();
void getFloat();   // prototype normally auto-generated by the Arduino preprocessor

int main() {
  setup();
  for (;;) loop();
}
